version: "3"
services:
  frontend-dev:
    container_name: frontend-dev
    build:
      context: ../
      dockerfile: dev/Dockerfile
    volumes:
      - ../public:/app/public
      - ../src:/app/src
      - ../package.json:/app/package.json
      - ../yarn.lock:/app/yarn.lock
    networks:
      - concrete-net
    ports:
      - 3000:3000

networks:
  concrete-net:
    external: true
